version: '3'

services:
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - gem_cache:/usr/local/bundle
    ports:
      - "3000:3000"

  redis:
    image: redis:7.0
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  database:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database

volumes:
  redis_data:
  db_data:
  gem_cache:

 